<?php

namespace alexeevdv\SumSub\Request;

final class ImportApplicantRequest
{
    /**
     * Share token generated by another subsub client
     *
     * @var string
     */
    private $shareToken;

    /**
     * No   Specify one or few comma-separated document types if an applicant
     * has to resubmit those documents to be verified.
     * Examples, SELFIE, IDENTITY, etc.
     *
     * @var array|null
     */
    private $resetIdDocSetTypes;

    /**
     * If you trust your partner's check result, then you should use true.
     * If it is false, then the applicant will be rechecked. false as default
     *
     * @var bool|null
     */
    private $trustReview;

    /**
     * Sets your own externalUserId for the imported applicant.
     * In case of empty value we'll generate a random one.
     *
     * @var string|null
     */
    private $userId;


    /**
     * Sets specified levelName to imported applicant and sets
     * init in case not all required documents present.
     *
     * @var string|null
     */
    private $levelName;

    /**
     * ImportApplicantRequest  constructor
     *
     * @param string $shareToken
     * @param array|null $resetIdDocSetTypes
     * @param bool|null $trustReview
     * @param string|null $userId
     * @param string|null $levelName
     */
    public function __construct(
        $shareToken,
        $resetIdDocSetTypes = null,
        $trustReview = null,
        $userId = null,
        $levelName = null
    ) {
        $this->shareToken = $shareToken;
        $this->resetIdDocSetTypes = $resetIdDocSetTypes;
        $this->trustReview = $trustReview;
        $this->userId = $userId;
        $this->levelName = $levelName;
    }

    /**
     * @return string
     */
    public function getShareToken()
    {
        return $this->shareToken;
    }

    /**
     * @return array|null
     */
    public function getResetIdDocSetTypes()
    {
        return $this->resetIdDocSetTypes;
    }

    /**
     * @return bool|null
     */
    public function getTrustReview()
    {
        return $this->trustReview;
    }

    /**
     * @return string|null
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * @return string|null
     */
    public function getLevelName()
    {
        return $this->levelName;
    }
}
